# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Postcodeanywhere-BACS-REST
version:      0.01
version_from: lib/WebService/Postcodeanywhere/BACS/REST.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0.02
    XML::Twig:                     3.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
